language: cpp

dist: focal

compiler:
          - gcc

before_install:
          - sudo sh -c 'echo "deb http://www.icub.org/ubuntu focal contrib/science" > /etc/apt/sources.list.d/icub.list'
          - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 57A5ACB6110576A6
          - sudo apt update -qq
          
install:
          - sudo apt install -qq cmake build-essential yarp

before_script:
          - mkdir build
          - cd build
          - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$MYDIR/yarp/build -DBUILD_APPLICATIONS=ON -DBUILD_HARDWAREIO=ON -DBUILD_PROCESSING=ON -DENABLE_autosaccade=ON -DENABLE_binarydumper=ON -DENABLE_calibrate=ON -DENABLE_corner=ON -DENABLE_vCluster=ON -DENABLE_vFramer=ON -DENABLE_vPreProcess=ON -DENABLE_vSkinInterface=ON -DENABLE_view=ON -DENABLE_zynqgrabber=ON

script: make -j 2
